### ISSUE TITLE
Build error: "Did you forget to add '#include "pch.h"' to your source?

### ISSUE THREAD

**Issue by Darthagnon** [Lyut/SpotiHook#2]
Greetings, Lyut

I am attempting to build the project using Visual Studio 2019 Build Tools, but I'm getting the error:
``` Did you forget to add '#include "pch.h"' to your source?``` This error appears for dllmain.cpp, overlay.cpp, zgui.cc, but adding the required include to the files throws up other errors. I have the XSpotify-master. 

Any chance you could help, or do you have any precompiled binaries?

**Comment by Lyut** [comment]
Hello Darren,
If you're using Visual Studio you most likely forgot to turn off precompiled headers from the project configuration, under the "C/C++" tab.

Keep in mind the offsets are hardcoded and might not work for the current Spotify version. I will check tomorrow if there have been new updates and eventually update the offsets.

**Comment by thelucifermorningstar** [comment]
@Darthagnon 
This fixes your issue: https://stackoverflow.com/a/54102011

@Lyut 
However, then 109 errors pop up. 
The one I've tried to fix is: `'Cannot open include file: 'd3dx9.h': No such file or directory'`
by installing the DirectX SDK, which lead to another issue during install, which I fixed using:
http://jaewon.hwang.info/jaewon/2015/05/08/s1023-error-when-you-install-the-directx-sdk-june-2010/

Then, I had to include its path/source to your source by doing this: https://stackoverflow.com/a/42654539

Now 315 errors show up xD
The readme shows 3 libraries used, assuming those are already in your source, right?




![image](https://user-images.githubusercontent.com/37758237/84829013-508f4080-b027-11ea-854c-9ff859832ec1.png)

**Comment by Darthagnon** [comment]
Glad to see I'm not the only one! I managed to switch off using precompiled headers, but then I saw those hundreds of errors pop up, too. I tried fixing one or two, by linking to libs I already have installed with Qt, but gave up after a while.

@thelucifermorningstar, the project requires libs from XSpotify (which was removed from GitHub), but there's a mirror [here](https://codeberg.org/uhwot/XSpotify/)

**Comment by Lyut** [comment]
It doesn't require XSpotify lib, it's basically a fork.

You need to include your DirectX SDK and also set your project to multibyte character set.

**Comment by thelucifermorningstar** [comment]
@Lyut 
Thank you.
I switched it to x86 release and now I got a .dll compiled, see attachment.
[SpotiHook.zip](https://github.com/Lyut/SpotiHook/files/4789790/SpotiHook.zip)

Now , how to use? 
Just plump it in %appdata%/roaming/Spotify folder and start Spotify.exe?

By the way, you can download older versions here if needed:
https://github.com/CHEF-KOCH/Spotify-Ad-free/releases/


@Darthagnon 
I had to install OpenSSL using one from here: https://slproweb.com/products/Win32OpenSSL.html
Then I added the path using this: https://stackoverflow.com/a/31322172
I had to change `libcryptoMT.lib` to `libcrypto32MT.lib` in `patchDownloads.h` since i installed a 32-bit version of OpenSSL.

See screenshots which may help you.
![image](https://user-images.githubusercontent.com/37758237/84843488-4f224000-b048-11ea-9ba5-9100d6919db6.png)

![image](https://user-images.githubusercontent.com/37758237/84843496-577a7b00-b048-11ea-9450-c6acaf2419c2.png)

**Comment by Lyut** [comment]
If you are looking for just a fork of XSpotify this project probably isn't for you. In fact, it's even more complex to compile than XSpotify because it also requires the DirectX SDK

Regardless of that, in the recent updates Spotify has changed their aes_set_encrypt_key function, with a new argument that gets passed and a new algorithm to scramble the key, which I haven't reversed yet. This means, while you are able to skip ads, you still won't be able to download songs from this unless someone wants to sit down in front of it (I probably won't) 

if you take a look at patchDownloads.h you can see I commented the hook for aes_set_encrypt_key
